kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7
  commands:
  - vendor/bin/phpunit tests

- name: push to packagist.org
  image: curlimages/curl:latest
  commands: >-
    curl -X POST -H "content-type:application/json"
    "https://packagist.org/api/update-package?username=benharri&apiToken=$API_TOKEN"
    -d'{"repository":{"url":"PACKAGIST_PACKAGE_URL"}}'
  environment:
    API_TOKEN:
      from_secret: API_TOKEN
  when:
    event:
    - tag

